version: '3.4'
services:
  postgres:
    container_name: 'mixin-gist-be-db'
    image: postgres:11.15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mixin-gist
    volumes:
      - 'dbdata:/var/lib/postgresql/data'
  
volumes:
  dbdata:
    name: mixin-gist
